[package]
name = "scribe"
version = "0.3.8"
edition = "2021"
authors = ["gnacho"]
description = "A native GNOME Markdown editor"
rust-version = "1.83"
license = "AGPL-3.0-or-later"

[dependencies]
gtk4 = { version = "0.9", features = ["v4_14"] }
libadwaita = { version = "0.7", features = ["v1_5"] }
gtksourceview5 = { version = "0.9", package = "sourceview5", features = ["v5_10"] }
glib = "0.20"
gio = "0.20"
gdk4 = "0.9"
pulldown-cmark = "0.12"
